tax: 0.01                                   # 1% tax
auction-setup-time: 30                      # the time it takes to put an item on auction
default-max-auctions: 10
sold-message: true                          # send a message to the player when one of their auctions is sold
auto-collect: false                         # automatically gives the money to the player when an auction is bought and removes it from the ah
partial-selling: false                      # allows players to select the amount of items they want to buy of an auction
admin-permission: "auctionhouse.moderator"
display-update: 20                          # 20 ticks = 1 second, how frequently the item displays are updated; can be set to 1 for instant updates
auction-announcements: true                 # announce when someone puts an item on auction (players can toggle this with /ah announce)
bin-auctions: true                          # BIN = Buy It Now [/ah sell <amount>]
bin-auction-duration: 172800                # the time an auction lasts in seconds (60*60*48 = 172800)
min-bin: 1                                  # the minimum sell price
bid-auctions: true                          # enables actual auctions by typing [/ah bid <amount>]
bid-auction-duration: 7200                  # the time a bidding auction lasts in seconds (60*60*2 = 7200)
min-bid: 1                                  # the minimum bid price
last-bid-extra-time: 60                     # if the auction time is less than this when a bid is placed, it's set to this
bid-increase-percent: 25                    # how much each bid has to increase at least